# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  emsapi:
    image: emsapi
    build:
      context: .
      dockerfile: backend/src/EMS.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5294:5294
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
