# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  ems.sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ems.SqlServer
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=docker@Password123
      - MSSQL_PID=Express
    volumes:
      - ./.containers/sqlserver/data:/var/opt/mssql/data

  ems.api:
    image: emsapi
    build:
      context: .
      dockerfile: backend/src/EMS.Api/Dockerfile
    ports:
      - 5000:5000
  
  ems.react:
    image: emsreact
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - ems.api
    environment:
      - REACT_APP_API_URL=http://ems.api:5000